services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: value
  frontend:
    build:
      context: newordle-frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - backend
